import os
from dotenv import load_dotenv

load_dotenv(override=True)

LLM_DEPLOYMENT_NAME = os.getenv("LLM_DEPLOYMENT_NAME")
AZURE_COMPUTER_VISION_ENDPOINT = os.getenv("AZURE_COMPUTER_VISION_ENDPOINT")
AZURE_COMPUTER_VISION_API_KEY = os.getenv("AZURE_COMPUTER_VISION_API_KEY")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
